stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
  data_transformation:
    cmd: python src/data_transformation.py
    deps:
      - src/data_transformation.py
      - data/
    outs:
      - data/processed/

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/
    params:
      - epochs
      - lr
    outs:
      - models/

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/
    metrics:
      - metrics.json